### PR TITLE
Deployment cloud

### PR DESCRIPTION
**Pull request by AndreIglesias**
Contributions:
| File         | Description     | 
|--------------|-----------|
| client/setup.py | find_version parsing      |
| client/src/bastionlab/version.py    | libtorch version and links  |
| server/Docker.gpu.sev | docker image with gpu access |
| server/build.sh | automated build for the server on different linux distros |
| docs/docs/getting-started/installation.md | documentation for build.sh and docker image with gpu access |

### CODE REVIEW

**Review by JoFrost — APPROVED** [review]
Looks great, thank you!

**Review by dhalf — COMMENTED** [review]
You don't seem to pass the CUDA envar to make in build.sh
Is it still possible to change the CUDA install directory?
Also you pass LIBTORCH_PASS instead of LIBTORCH which bypasses the envars processing in the Makefile which means LD_LIBRARY_PATH is probably not correctly set

**Comment by JoFrost** [comment]
It looks like there was a confusion with BastionAI makefile, which use LIBTORCH_PATH.

**Comment by AndreIglesias** [comment]
> there was a confusion with BastionAI makefile, which use LIBTORCH_PATH.

Also with the [installation section](https://github.com/mithril-security/bastionlab/blob/96edd3a624847ed8aa55de8c4987937e9126f214/docs/docs/getting-started/installation.md?plain=1#L92) from the documentation which also uses LIBTORCH_PATH.

**Comment by AndreIglesias** [comment]
Now it is compatible with the envars from the Makefile.

**Review by dhalf — COMMENTED** [review]
Hey! Thanks for the changes :-)
A few more questions regarding the dependencies:
- Do we still need patchelf?
- Why is python3 required on the server side?
- How do you handle the rust toolchain?
- Why is sudo needed? Even if it is, installing it in a script is a bad idea as sudo need correctly be configured anyway

**Comment by AndreIglesias** [comment]
> Do we still need patchelf?

It seems like not anymore, I have **removed** it from the dependencies

> Why is python3 required on the server side?

It is used to run the python script that obtains the _libtorch link_ from the **version.py** file and downloads _libtorch.zip_ from there.

> How do you handle the rust toolchain?

I've added the **INSTALL_RUST_OPT** variable to set the installation _rustup options_ (To choose the default host, **toolchain**, profile, ...).
### Example:
```bash
export INSTALL_RUST_OPT='--profile minimal --default-toolchain nightly'
./build.sh
```

> Why is sudo needed? Even if it is, installing it in a script is a bad idea as sudo need correctly be configured anyway

The script should be run **without sudo** for just building the server, but in case it detects a dependency missing for the running distro, only then, it will launch an installation of those dependencies using **sudo** and then continue building **without** superuser privileges.

I have **removed** the installation of the **sudo** command and when is not installed it will prompt how to install the dependencies with the script.

**Review by dhalf — APPROVED** [review]

**Pull request merged**
