### PR TITLE
Adds challenge checking to auth

### PR DESCRIPTION
**Pull request by kbamponsem**

### CODE REVIEW

**Comment by dhalf** [comment]
Please reformat :-)

**Comment by ShannonSD** [comment]
The failed check seems to be a glitch in the CI as the pull_request and push checks are the same and the push check passed while the pull_request check failed.

**Comment by ShannonSD** [comment]
There's a bigger issue here. Tokens aren't being used as designed. Needs to be fixed before merge.

**Comment by ShannonSD** [comment]
Don't merge this PR yet. There session creation functionality needs to be redesigned.

**Review by dhalf — CHANGES_REQUESTED** [review]
I would be glad to merge this but we first need to change the notebooks (e.g. Quick Tour) accordingly.
Please explicitly pass the env var to disable authentication in all docker run commands in the notebook that rely on the fact that there's no authentication.
I guess all notebooks except the authentication tuto.

**Review by dhalf — APPROVED** [review]

**Pull request merged**
